# v8 VCF, GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz
vcf: "/scratch/groups/rmccoy22/aseyedi2/sQTLv8/data/vcf/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.vcf.gz"

sprime_dir: "/scratch/groups/rmccoy22/aseyedi2/sQTLv8/sprime"

# 1kg project direcotry (1kg-hs37d5/)
kg_dir: "/work-zfs/rmccoy22/resources/1kg-GRCh38"

# merged archaic VCFs
arch_vcf: "/scratch/groups/rmccoy22/aseyedi2/sQTLv8/spliceai"
