# data dir
data: "data/"
# WGS VCF
vcf: "{/path/to/}phg000830.v1.GTEx_WGS.genotype-calls-vcf.c1/GTEx_Analysis_2016-01-15_v7_WholeGenomeSeq_635Ind_PASS_AB02_GQ20_HETX_MISS15_PLINKQC.vcf.gz"

# sprime calls
sprime: "metadata/sprime/sprime_calls.txt"

# download leafcutter
leafcutter: {path/to/LC}

backupdir: