channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - htslib=1.9
  - bcftools=1.9
  - gatk4=4.1.3.0
  - r=3.5
  - python=2.7
  - r-data.table=1.12.2
  - r-r.utils=2.9.0
  - r-tidyverse=1.2.1
  - bioconductor-homo.sapiens=1.3.1
  - r-qqman=0.1.4
  - bioconductor-qvalue=2.16.0